name: Deploy to Azure (Simple)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: hadonas/rag-qna-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: hadonas/rag-qna-service:latest
        
    - name: Setup Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        version: '2.0.0'
        
    - name: Update App Service Environment Variables
      run: |
        echo "Updating environment variables..."
        
        # 환경 변수 설정 (GitHub Secrets에서 가져옴)
        az webapp config appsettings set \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --settings \
            AZURE_OPENAI_API_KEY="${{ secrets.AZURE_OPENAI_API_KEY }}" \
            AZURE_OPENAI_ENDPOINT="${{ secrets.AZURE_OPENAI_ENDPOINT }}" \
            AZURE_OPENAI_API_VERSION="${{ secrets.AZURE_OPENAI_API_VERSION }}" \
            MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            MONGO_DB="${{ secrets.MONGO_DB }}" \
            MONGO_COLL="${{ secrets.MONGO_COLL }}" \
            AZURE_OPENAI_CHAT_DEPLOYMENT="${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT }}" \
            AZURE_OPENAI_EMB_DEPLOYMENT="${{ secrets.AZURE_OPENAI_EMB_DEPLOYMENT }}" \
            MONGO_VECTOR_INDEX="${{ secrets.MONGO_VECTOR_INDEX }}" \
            MONGO_TEXT_INDEX="${{ secrets.MONGO_TEXT_INDEX }}"
            
    - name: Restart App Service
      run: |
        az webapp restart \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${{ env.AZURE_WEBAPP_NAME }}
          
    - name: Health Check
      run: |
        echo "Waiting for app to start..."
        sleep 30
        
        # 헬스체크 시도
        APP_URL="https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "Checking health at: $APP_URL/health"
        
        # 최대 5번 시도
        for i in {1..5}; do
          if curl -f "$APP_URL/health" > /dev/null 2>&1; then
            echo "✅ App is healthy!"
            break
          else
            echo "⏳ Attempt $i: App not ready yet, waiting..."
            sleep 10
          fi
        done
